[book]
authors = ["Alistair Keiller"]
language = "en"
src = "src"
title = "Anteater Electric Racing Documentation"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
no-section-label = true
